.Dd Nov 25, 2005
.Os ISO C99
.Dt META_OPTIONS 3
.Sh NAME
.Nm black76()
.Nd black76
.Sh SYNOPSIS
.Fd #include <metaoptions.h>
.Fo "double black76"
.Fa "int fCall"
.Fa "double F"
.Fa "double X"
.Fa "double T"
.Fa "double r"
.Fa "double v"
.Fc
.Fo "static inline double black76_put"
.Fa "double F"
.Fa "double X"
.Fa "double T"
.Fa "double r"
.Fa "double v"
.Fc
.Fo "static inline double black76_call"
.Fa "double F"
.Fa "double X"
.Fa "double T"
.Fa "double r"
.Fa "double v"
.Fc
.Sh DESCRIPTION
.Ss Arguments
.Bl -item
.It
.Fa F
.It
.Fa S
is the price of the underlying security. 
.It
.Fa T
is time to expiry as fraction of year. 6 months == 0.5, 9 months == 0.75
.It
.Fa r
is the risk free interest rate. 10% == 0.10
.It
.Fa v
Volatility, 30% == 0.30
.El
.Sh RETURN VALUE
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
