.Dd Nov 25, 2005
.Os ISO C99
.Dt META_OPTIONS 3
.Sh NAME
.Nm cbnd()
.Nd cbnd
.Sh SYNOPSIS
.Fd #include <metaoptions.h>
.Fo "double cbnd"
.Fa "double a"
.Fa "double b"
.Fa "double rho"
.Fc
.Sh DESCRIPTION
.Nm
computes the Cumulative Bivariate Normal Distribution 
.Sh RETURN VALUE
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
