.Dd Nov 25, 2005
.Os ISO C99
.Dt META_OPTIONS 3
.Sh NAME
.Nm cnd()
.Nd Calculate the cumulative normal probability.
.Sh SYNOPSIS
.Fd #include <metaoptions.h>
.Fo "double cnd"
.Fa "double x"
.Fc
.Sh DESCRIPTION
Cumulative Normal Distribution 
.Sh RETURN VALUE
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
