.Dd Nov 25, 2005
.Os ISO C99
.Dt META_OPTIONS 3
.Sh NAME
.Nm ComplexChooser()
.Nd ComplexChooser
.Sh SYNOPSIS
.Fd #include <metaoptions.h>
.Fo "double ComplexChooser"
.Fa "double S"
.Fa "double Xc"
.Fa "double Xp"
.Fa "double T"
.Fa "double Tc" 
.Fa "double Tp"
.Fa "double r"
.Fa "double b"
.Fa "double v"
.Fc
.Sh DESCRIPTION
.Sh RETURN VALUE
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
