.Dd Nov 25, 2005
.Os ISO C99
.Dt META_OPTIONS 3
.Sh NAME
.Nm DiscreteAdjustedBarrier()
.Nd DiscreteAdjustedBarrier
.Sh SYNOPSIS
.Fd #include <metaoptions.h>
.Fo "double DiscreteAdjustedBarrier"
.Fa "double S"
.Fa "double H"
.Fa "double v"
.Fa "double dt"
.Fc
.Sh DESCRIPTION
.Sh RETURN VALUE
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
