.Dd Nov 25, 2005
.Os ISO C99
.Dt META_OPTIONS 3
.Sh NAME
.Nm EuropeanExchangeOption()
.Nd EuropeanExchangeOption
.Sh SYNOPSIS
.Fd #include <metaoptions.h>
.Fo "double EuropeanExchangeOption"
.Fa "double S1"
.Fa "double S2"
.Fa "double Q1"
.Fa "double Q2"
.Fa "double T"
.Fa "double r"
.Fa "double b1"
.Fa "double b2"
.Fa "double v1"
.Fa "double v2"
.Fa "double rho"
.Fc
.Sh DESCRIPTION
.Sh RETURN VALUE
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
