.Dd Nov 25, 2005
.Os ISO C99
.Dt META_OPTIONS 3
.Sh NAME
.Nm ExchangeExchangeOption()
.Nd ExchangeExchangeOption
.Sh SYNOPSIS
.Fd #include <metaoptions.h>
.Fo "double ExchangeExchangeOption"
.Fa "int TypeFlag"
.Fa "double S1"
.Fa "double S2"
.Fa "double q"
.Fa "double t1"
.Fa "double T2"
.Fa "double r"
.Fa "double b1"
.Fa "double b2"
.Fa "double v1"
.Fa "double v2"
.Fa "double rho"
.Fc
.Sh DESCRIPTION
.Sh RETURN VALUE
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
