.Dd Nov 25, 2005
.Os ISO C99
.Dt META_OPTIONS 3
.Sh NAME
.Nm MiltersenSchwartz()
.Nd MiltersenSchwartz
.Sh SYNOPSIS
.Fd #include <metaoptions.h>
.Fo "double MiltersenSchwartz"
.Fa "int fCall"
.Fa "double Pt"
.Fa "double FT"
.Fa "double X"
.Fa "double t1"
.Fa "double T2"
.Fa "double vS"
.Fa "double vE"
.Fa "double vf"
.Fa "double rhoSe"
.Fa "double rhoSf"
.Fa "double rhoef"
.Fa "double Kappae"
.Fa "double Kappaf"
.Fc
.Sh DESCRIPTION
.Sh RETURN VALUE
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
