.Dd Nov 25, 2005
.Os ISO C99
.Dt META_OPTIONS 3
.Sh NAME
.Nm PartialFloatLB()
.Nd PartialFloatLB
.Sh SYNOPSIS
.Fd #include <metaoptions.h>
.Fo "double PartialFloatLB"
.Fa "int fCall"
.Fa "double S"
.Fa "double SMin"
.Fa "double SMax"
.Fa "double t1"
.Fa "double T2"
.Fa "double r"
.Fa "double b"
.Fa "double v"
.Fa "double lambda"
.Fc
.Sh DESCRIPTION
.Sh RETURN VALUE
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
