.Dd Nov 25, 2005
.Os ISO C99
.Dt META_OPTIONS 3
.Sh NAME
.Nm Quanto()
.Nd Quanto
.Sh SYNOPSIS
.Fd #include <metaoptions.h>
.Fa "double Quanto"
.Fa "int fCall"
.Fa "double Ep"
.Fa "double S"
.Fa "double X"
.Fa "double T"
.Fa "double r"
.Fa "double rf"
.Fa "double q"
.Fa "double vS"
.Fa "double vE"
.Fa "double rho"
.Fc
.Sh DESCRIPTION
.Sh RETURN VALUE
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
