.Dd Nov 25, 2005
.Os ISO C99
.Dt META_OPTIONS 3
.Sh NAME
.Nm RollGeskeWhaley()
.Nd RollGeskeWhaley
.Sh SYNOPSIS
.Fd #include <metaoptions.h>
.Fo "double RollGeskeWhaley"
.Fa "double S"
.Fa "double X"
.Fa "double t1"
.Fa "double T2"
.Fa "double r"
.Fa "double d"
.Fa "double v"
.Fc
.Sh DESCRIPTION
/* American Calls on stocks with known dividends, Roll-Geske-Whaley */
/*t1 time to dividend payout */
/*T2 time to option expiration */
.Sh RETURN VALUE
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
