.Dd Nov 25, 2005
.Os ISO C99
.Dt META_OPTIONS 3
.Sh NAME
.Nm SpreadApproximation()
.Nd SpreadApproximation
.Sh SYNOPSIS
.Fd #include <metaoptions.h>
.Fo "double SpreadApproximation"
.Fa "int fCall"
.Fa "double f1"
.Fa "double f2"
.Fa "double X"
.Fa "double T"
.Fa "double r"
.Fa "double v1"
.Fa "double v2"
.Fa "double rho"
.Fc
.Sh DESCRIPTION
.Sh RETURN VALUE
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
