.Dd Nov 25, 2005
.Os ISO C99
.Dt META_OPTIONS 3
.Sh NAME
.Nm Swapoption()
.Nd Swapoption
.Sh SYNOPSIS
.Fd #include <metaoptions.h>
/* Black-76 European swap option */
.Fo "double Swapoption"
.Fa "int fCall"
.Fa "double t1"
.Fa "double m"
.Fa "double F"
.Fa "double X"
.Fa "double T"
.Fa "double r"
.Fa "double v"
.Fc
.Sh DESCRIPTION
.Sh RETURN VALUE
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
