.Dd Nov 25, 2005
.Os ISO C99
.Dt META_OPTIONS 3
.Sh NAME
.Nm TurnbullWakemanAsian()
.Nd TurnbullWakemanAsian
.Sh SYNOPSIS
.Fd #include <metaoptions.h>
.Fo "double TurnbullWakemanAsian"
.Fa "int fCall"
.Fa "double S"
.Fa "double SA"
.Fa "double X"
.Fa "double T"
.Fa "double T2"
.Fa "double tau"
.Fa "double r"
.Fa "double b"
.Fa "double v"
.Fc
.Sh DESCRIPTION
.Sh RETURN VALUE
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
