.Dd Nov 25, 2005
.Os ISO C99
.Dt META_OPTIONS 3
.Sh NAME
.Nm TwoAssetBarrier()
.Nd TwoAssetBarrier
.Sh SYNOPSIS
.Fd #include <metaoptions.h>
.Fo "double TwoAssetBarrier"
.Fa "int type"
.Fa "double S1"
.Fa "double S2"
.Fa "double X"
.Fa "double H"
.Fa "double T"
.Fa "double r"
.Fa "double b1"
.Fa "double b2"
.Fa "double v1"
.Fa "double v2"
.Fa "double rho"
.Fc
.Sh DESCRIPTION
.Sh RETURN VALUE
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
