.Dd Nov 25, 2005
.Os ISO C99
.Dt META_OPTIONS 3
.Sh NAME
.Nm VasicekBondOption()
.Nd VasicekBondOption
.Sh SYNOPSIS
.Fd #include <metaoptions.h>
.Fo "double VasicekBondOption"
.Fa "int fCall"
.Fa "double F"
.Fa "double X"
.Fa "double tau"
.Fa "double T"
.Fa "double r"
.Fa "double theta"
.Fa "double kappa"
.Fa "double v"
.Fc
.Sh DESCRIPTION
.Sh RETURN VALUE
.Sh AUTHOR
.An B. Augestad, bjorn.augestad@gmail.com
